import pymongo
from pymongo import MongoClient
label = input("Type in a label name to search for sessions and users: \n")
#initialize MongoDB
client = MongoClient()
client = MongoClient("mongodb://localhost:27017")
mydatabase = client['twitterAPI']
mycollection = mydatabase['downloads']

user = []
screen = []
date = []
img_index = []
for i in mydatabase.downloads.find({'label': label}):
	user.append(i['user_name'])
	screen.append(i['screen_name'])
	date.append(i['date'])
	img_index.append(i['img_index'])

for i in range(0,len(user)):
	print("--------------------------------------")
	print("the No.",i+1," label",label," is generated by:")
	print("*user:",user[i])
	print("*searched screen:",screen[i])
	print("*date:",date[i])
	print("*img_index:", img_index[i])
