import pymysql
import emoji

label = input("Type in a label name to search for sessions and users: \n")
session_id = []
data = []
conn = pymysql.connect('localhost', 'root', 'root', 'TwitterAPI')
with conn.cursor() as cursor:
	sql = """SELECT session_id,img_index FROM LABEL WHERE label_name = %s"""
	cursor.execute(sql,(label))
	session_id.append(cursor.fetchall())
	#print(session_id[0])
for i in range(0, len(session_id[0])):
	session = session_id[0][i][0]
	#print(session)
	with conn.cursor() as cursor:
		sql = """SELECT user_name, screen_name, session_time FROM SESSION WHERE id = %s"""
		cursor.execute(sql,(session))
		data.append(cursor.fetchall())

for i in range(0,len(session_id[0])):	
	user = data[i][0][0]
	screen = data[i][0][1]
	date = data[i][0][2]
	img = session_id[0][i][1]
	print("--------------------------------------")
	print("the No.",i+1," label",label," is generated by:")
	print("*user:",user)
	print("*searched screen:",screen)
	print("*date:",date)
	print("*img_index:", img)